-- MySQL Script generated by MySQL Workbench
-- Tue Jul 12 19:34:57 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema retail_store
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `retail_store` ;

-- -----------------------------------------------------
-- Schema retail_store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `retail_store` DEFAULT CHARACTER SET utf8 ;
USE `retail_store` ;

-- -----------------------------------------------------
-- Table `retail_store`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retail_store`.`Address` (
  `address_code` SMALLINT NOT NULL AUTO_INCREMENT,
  `public_place` VARCHAR(50) NOT NULL,
  `street_name` VARCHAR(40) NOT NULL,
  `number_of_street` SMALLINT NOT NULL,
  `complement` VARCHAR(10) NULL,
  `neighborhood` VARCHAR(50) NOT NULL,
  `city` VARCHAR(30) NOT NULL,
  `zipcode` CHAR(8) NOT NULL,
  PRIMARY KEY (`address_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retail_store`.`Provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retail_store`.`Provider` (
  `provider_code` SMALLINT NOT NULL AUTO_INCREMENT,
  `cnpj` CHAR(18) NOT NULL,
  `provider_name` VARCHAR(50) NOT NULL,
  `provider_phone` CHAR(14) NOT NULL,
  `address_code` SMALLINT NOT NULL,
  PRIMARY KEY (`provider_code`),
  INDEX `fk_Provider_Address` (`address_code` ASC) VISIBLE,
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_Provider_Address`
    FOREIGN KEY (`address_code`)
    REFERENCES `retail_store`.`Address` (`address_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retail_store`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retail_store`.`Product` (
  `product_code` SMALLINT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NOT NULL,
  `product_price` DECIMAL(10,2) NOT NULL,
  `product_quantity` SMALLINT NOT NULL,
  PRIMARY KEY (`product_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retail_store`.`Provider_Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retail_store`.`Provider_Product` (
  `provider_code` SMALLINT NOT NULL,
  `product_code` SMALLINT NOT NULL,
  PRIMARY KEY (`provider_code`, `product_code`),
  INDEX `fk_Provider_Product_Product` (`product_code` ASC) VISIBLE,
  INDEX `fk_Provider_Product_Provider` (`provider_code` ASC) VISIBLE,
  CONSTRAINT `fk_Provider_has_Product_Provider1`
    FOREIGN KEY (`provider_code`)
    REFERENCES `retail_store`.`Provider` (`provider_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Provider_has_Product_Product1`
    FOREIGN KEY (`product_code`)
    REFERENCES `retail_store`.`Product` (`product_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
